version: "3.9"
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - crud-db:/var/lib/docker/volumes/crud-db/_data
      - ./src/db-restore/nodegmp-base.sql:/docker-entrypoint-initdb.d/nodegmp-base.sql
  app:
    build: .
    depends_on:
      - database
    ports:
    - target: 3000
      host_ip: 127.0.0.1
      published: 3003
      protocol: tcp
      mode: host
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
volumes:
  crud-db:
